//Nome: Ian Felix Fernandes Matrícula: 202376007

package Frames;

import Usuarios.Cliente;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;

public class TransferenciaCompletaFrame extends JFrame {
    private JFormattedTextField campoOrigem;
    private JFormattedTextField campoDestino;
    private JTextField campoValor;
    private JButton botaoTransferir;
    private JPanel transferenciaCompletaPanel;
    private JButton botaoCancelar;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    public TransferenciaCompletaFrame() {

        setSize(400, 250);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setContentPane(transferenciaCompletaPanel);
        Utility.aplicaMascaraCpf(campoOrigem);
        Utility.aplicaMascaraCpf(campoDestino);
        Utility.adicionaBotaoCancelarOperacao(botaoCancelar, this);


        botaoTransferir.addActionListener(e -> {
            Cliente origem = Utility.encontraCliente(campoOrigem.getText());
            Cliente destino = Utility.encontraCliente(campoDestino.getText());
            double valor = Utility.confereValorDouble(campoValor);
            origem.transferir(origem, destino, valor);
            dispose();
        });

        campoValor.addFocusListener(new FocusAdapter() {
            @Override
            public void focusLost(FocusEvent e) {
                Utility.formataValor(campoValor);
            }
        });

    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        transferenciaCompletaPanel = new JPanel();
        transferenciaCompletaPanel.setLayout(new GridLayoutManager(4, 2, new Insets(0, 0, 0, 0), -1, -1));
        transferenciaCompletaPanel.setBorder(BorderFactory.createTitledBorder(null, "TRANSFERENCIA", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        final JLabel label1 = new JLabel();
        label1.setText("Conta origem");
        transferenciaCompletaPanel.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        campoOrigem = new JFormattedTextField();
        transferenciaCompletaPanel.add(campoOrigem, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("Conta destino");
        transferenciaCompletaPanel.add(label2, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        campoDestino = new JFormattedTextField();
        transferenciaCompletaPanel.add(campoDestino, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        botaoTransferir = new JButton();
        botaoTransferir.setText("Confirmar transferência");
        transferenciaCompletaPanel.add(botaoTransferir, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label3 = new JLabel();
        label3.setText("Valor");
        transferenciaCompletaPanel.add(label3, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        campoValor = new JTextField();
        transferenciaCompletaPanel.add(campoValor, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        botaoCancelar = new JButton();
        botaoCancelar.setText("Cancelar");
        transferenciaCompletaPanel.add(botaoCancelar, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return transferenciaCompletaPanel;
    }
}